version: '3'

services:
  web:
    build: .
    command: python hackernews/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/code
    ports:
    - "8000:8000"
    depends_on:
      - migration
  migration:
    command: python hackernews/manage.py migrate --noinput
    volumes:
    - .:/code
